### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [danesparza/iTunesSearch#10]
Hi @danesparza .. I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo/icon design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard.
Mirza zulfan.

**Comment by danesparza** [comment]
Sure @mirzazulfan - what are your thoughts?

**Comment by mirzazulfan** [comment]
Thanks for your response @danesparza . Can you give me some information about your project? or if you have an idea please share with me, it would be better for me.

**Comment by mirzazulfan** [comment]
Hi @danesparza .. I've designed a logo for your project, is there anything you want to change please let me know. 
![itunes search](https://user-images.githubusercontent.com/36124339/42432398-8a37f17e-8374-11e8-9e6f-1cc48f4be415.png)
