### ISSUE TITLE
Podcast search stalling

### ISSUE THREAD

**Issue by CharcoalStyles** [danesparza/iTunesSearch#4]
Grabbed the package from NuGet and dried implementing a basic search:
`iTunesSearchManager itsm = new iTunesSearchManager();`
`var items = itsm.GetPodcasts(query).Result;`
Basically copying and pasting from your tests.

But when I try to run it; it just stalls; both locally and live.
I'm trying to get it to run in an ASP.NET MVC app.

Any ideas why this could be happening?

**Comment by danesparza** [comment]
Hmmmm ... not sure why this might be happening.  

I pulled latest and ran the unit tests -- the [Podcast tests](https://github.com/danesparza/iTunesSearch/blob/master/iTunesSearch.Library.Tests/iTunesSearchTests.cs#L112-L139) seem to work just fine.  What version of .NET are you using?

**Comment by CharcoalStyles** [comment]
It's just a basic ASP.Net MVC application, from VS2015. The project  properties says it's running .Net 4.5.2
I've come across another library here on GitHub (but not on NuGet) that I was able to implement and get working, if it helps: https://github.com/waltersoto/iTunesSearch
If you need any more debugging, let me know and I'll help out!

**Comment by chad-albrecht** [comment]
I ran into this as well while calling from some sync methods.  I didn't realize they were async as the method wasn't GetPodcastsAsync().  Either way, the problem is the task can't rejoin the original context.  To solve this problem I changed the original GetPodcasts() to GetPodcastsAsync() and wrote the sync method like this:

```
 public PodcastListResult GetPodcasts(string podcast, int resultLimit = 100, string countryCode = "us")
        {
            Task<PodcastListResult> task = Task.Run<PodcastListResult>(async () => await GetPodcastsAsync(podcast, resultLimit, countryCode));

            return task.GetAwaiter().GetResult();
        }
```

Works like a champ now!
